/* Drafts for the hidden sections (see HIDDEN_SECTIONS.md). They live apart
   from content.ts on purpose: only the hidden pages import this file, and
   those pages aren't routed, so none of this ships in the public site. */

export const HIDDEN = {
  papers: {
    lede: "Papers I’ve read properly, slowly, with a pencil. The notes are more about what changed in my head than about the paper itself.",
    items: [
      {
        id: "mohanty-2016",
        title: "Using Deep Learning for Image-Based Plant Disease Detection",
        authors: "Sharada P. Mohanty, David P. Hughes, Marcel Salathé",
        year: 2016, venue: "Frontiers in Plant Science", topic: "Computer vision",
        why: "It’s the paper behind PlantVillage, the dataset I started Agnolense with.",
        core: "CNNs trained on a large, labelled set of leaf images can classify 26 diseases across 14 crops with very high accuracy.",
        insight: "The authors themselves note that accuracy drops sharply on images taken in different conditions. I read that sentence and ignored it. I shouldn’t have.",
        changed: "Limitations sections are the most important part of a paper.",
        questions: "How much field data is enough to close the gap? Is there a principled way to know?",
        related: ["agnolense"],
      },
      {
        id: "gradcam-2017",
        title: "Grad-CAM: Visual Explanations from Deep Networks via Gradient-based Localization",
        authors: "Ramprasaath R. Selvaraju, Michael Cogswell, Abhishek Das, et al.",
        year: 2017, venue: "ICCV", topic: "Interpretability",
        why: "I needed to know what my model was actually looking at.",
        core: "Use the gradients flowing into the last convolutional layer to produce a heatmap of the regions that mattered for a prediction.",
        insight: "A model can be right for the wrong reasons, and accuracy alone will never tell you.",
        changed: "I now treat explanation tools as debugging tools, not presentation tools.",
        questions: "How reliable are these heatmaps themselves? When do they mislead?",
        related: ["agnolense"],
      },
      {
        id: "efficientnet-2019",
        title: "EfficientNet: Rethinking Model Scaling for Convolutional Neural Networks",
        authors: "Mingxing Tan, Quoc V. Le",
        year: 2019, venue: "ICML", topic: "Computer vision",
        why: "I needed a model small enough to run on an old phone.",
        core: "Scale depth, width and resolution together with a fixed ratio, rather than scaling one dimension at a time.",
        insight: "Bigger isn’t the only direction. Balanced often beats bigger.",
        changed: "I started thinking about the deployment target before choosing an architecture.",
        questions: "How do these scaling rules change when the input data is very different from ImageNet?",
        related: ["agnolense"],
      },
      {
        id: "resnet-2015",
        title: "Deep Residual Learning for Image Recognition",
        authors: "Kaiming He, Xiangyu Zhang, Shaoqing Ren, Jian Sun",
        year: 2015, venue: "CVPR", topic: "Computer vision",
        why: "Everything I read referenced it. I wanted to understand why.",
        core: "Let layers learn a residual on top of an identity shortcut, which makes very deep networks trainable.",
        insight: "Sometimes the breakthrough is making the easy thing, doing nothing, easy for the network.",
        changed: "Simple structural ideas can matter more than clever new components.",
        questions: "Why do skip connections help optimisation so much? I understand the story, not the proof.",
        related: ["agnolense"],
      },
      {
        id: "attention-2017",
        title: "Attention Is All You Need",
        authors: "Ashish Vaswani, Noam Shazeer, Niki Parmar, et al.",
        year: 2017, venue: "NeurIPS", topic: "Sequence models",
        why: "To understand the architecture behind the tools I use every day.",
        core: "Replace recurrence entirely with attention, so every token can look at every other token in parallel.",
        insight: "Removing a constraint (sequential processing) unlocked scale more than adding anything did.",
        changed: "I stopped thinking of attention as mysterious. It’s a weighted lookup, a very well-placed one.",
        questions: "What are we losing by making everything attend to everything?",
        related: [],
      },
      {
        id: "isolation-forest-2008",
        title: "Isolation Forest",
        authors: "Fei Tony Liu, Kai Ming Ting, Zhi-Hua Zhou",
        year: 2008, venue: "ICDM", topic: "Anomaly detection",
        why: "Finscope needed to flag unusual transactions without labelled anomalies.",
        core: "Anomalies are few and different, so they’re easier to isolate with random splits. Fewer splits needed → more anomalous.",
        insight: "Instead of modelling “normal”, model how easy it is to separate something from everything else.",
        changed: "Reframing the problem can be more powerful than a better model.",
        questions: "How do you evaluate anomaly detection when you don’t know what the anomalies are?",
        related: ["finscope"],
      },
      {
        id: "prophet-2017",
        title: "Forecasting at Scale",
        authors: "Sean J. Taylor, Benjamin Letham",
        year: 2017, venue: "The American Statistician", topic: "Forecasting",
        why: "After my LSTM lost to a baseline, I wanted to understand what good forecasting actually looks like.",
        core: "A decomposable model, trend, seasonality, holidays, that analysts can understand and adjust.",
        insight: "A forecast people can reason about is worth more than a slightly better one they can’t.",
        changed: "Interpretability is a feature, especially for personal data.",
        questions: "Where’s the line between a model that’s simple enough to trust and too simple to be useful?",
        related: ["finscope"],
      },
      {
        id: "tabular-2021",
        title: "Tabular Data: Deep Learning is Not All You Need",
        authors: "Ravid Shwartz-Ziv, Amitai Armon",
        year: 2021, venue: "Information Fusion", topic: "Machine learning",
        why: "A sanity check after Finscope.",
        core: "On many tabular datasets, gradient-boosted trees still outperform deep models, and they’re cheaper to tune.",
        insight: "Choosing the tool for the data, not for the story you want to tell about the project.",
        changed: "“What’s the simplest thing that could work?” is now my first question.",
        questions: "Which properties of a dataset make deep learning worth it?",
        related: ["finscope"],
      },
      {
        id: "tech-debt-2015",
        title: "Hidden Technical Debt in Machine Learning Systems",
        authors: "D. Sculley, Gary Holt, Daniel Golovin, et al.",
        year: 2015, venue: "NeurIPS", topic: "ML systems",
        why: "Agnolense’s training code was fine. Everything around it was a mess.",
        core: "The model is a small box in the middle of a very large system, data pipelines, configuration, monitoring, and that’s where the debt accumulates.",
        insight: "The famous diagram: the ML code is the tiny square in the middle.",
        changed: "I budget more time for the plumbing than the model now.",
        questions: "What does good ML hygiene look like for a one-person project?",
        related: ["agnolense", "finscope"],
      },
    ],
  },

  journaling: {
    intro: [
      "Some things aren’t meant to be displayed.",
      "These are the pieces I chose to preserve.",
    ],
    entries: [
      // TODO: your own fragments. kinds: excerpt · question · changed · observation · reflection
      { date: "2024-01-09", kind: "excerpt", text: "Ran today. Not well. But I went, which is the only part I promised myself." },
      { date: "2024-04-22", kind: "question", text: "Do I like programming, or do I like the feeling of finally understanding something? Does it matter?" },
      { date: "2024-07-15", kind: "changed", before: "Being busy means making progress.", after: "Being busy is often how I avoid deciding what matters." },
      { date: "2024-10-03", kind: "observation", text: "I write better code in the morning and better sentences at night. I should stop fighting that." },
      { date: "2025-02-18", kind: "excerpt", text: "The model was 98% accurate and completely wrong. There’s probably a lesson in that about more than models." },
      { date: "2025-06-30", kind: "reflection", text: "Half a year of these pages and the same three worries keep coming back. Maybe that’s what they’re for, to notice what keeps coming back." },
      { date: "2025-09-11", kind: "changed", before: "Asking questions makes me look like I don’t know things.", after: "Asking questions is how I stop not knowing things." },
      { date: "2025-11-19", kind: "observation", text: "Thought about the fig tree again. Maybe the trick isn’t choosing faster, it’s noticing that you can come back for more than one." },
      { date: "2026-01-01", kind: "question", text: "What would I build if no one were ever going to see it?" },
      { date: "2026-05-27", kind: "observation", text: "The rain smelled like the first week of college. Some memories are stored in weather." },
      { date: "2026-09-02", kind: "excerpt", text: "I don’t journal to remember. I journal to find out what I already think." },
    ],
  },
};
